bin/covergroupgen.py

Testing PR

---

bin/covergroupgen.py
bin/testgen.py

I noticed that the python files in the `bin` directory had their main body without any conditions, so I added it for future code reusability

put main body in conditional to follow best practices

---

bin/covergroupgen.py

Modified covergroupgen.py to generate a new block for 'mv' instruction in covergroup.svh file.

100% coverage of RV32 addi achieved

---

bin/testgen.py

This function had an error, I changed line 199 of testgen.py to :
lines = lines + test + " " + reg + str(rdb) + ", " + reg + str(rs1b) + ", " + reg + str(rs2b) + " # perform first operation\n" 
Now, it's working as desired.

Resolved error in writeHazardVector function

---

bin/testgen.py
templates/sample_RV32Zca.txt

coverage improved from 81% to  91.97%.

improving coverage of RV32 c.addi

---

bin/testgen.py

76-78% coverage for all FR4 type instructions

bug fix for FR4 and FR-type instructions

---

bin/covergroupgen.py

Edited the covergroupgen file so as to address the problem of pseudo-instructions of bne , blt and bge

Improved coverage for bne , blt , bge 

---

bin/testgen.py

Trying to get the coverage of c.lw, but coverage remains zeros for even cp_rd_toggle and cp_rdp.

Test Script for c.lw

---

bin/testgen.py
templates/cmp_rd_rs1_c.txt
testplans/RV32Zca.csv

Managed to get 100% coverage of "c.lw"
Luckily, 100% coverage of c.sw has been achieved from the test generated for "c.lw" because I was using c.sw in them.
Should I generate separate tests for "c.sw" ?

c.lw 100% Coverage.

---

bin/testgen.py
testplans/RV32Zca.csv

100% coverage of c.sw achieved after unchecking all the coverpoints of c.lw to ensure that its each bin is getting hit because of its own tests. i.e,
Covergroup instance obj_c_lw                             0.00%        100          -    Uncovered
Covergroup instance obj_c_sw                         100.00%        100          -    Covered

c.sw 100% coverage

---

templates/sample_RV64Zca.txt

Tried to write it by looking at sample of RV32Zca Version and added the RV64Zca instructions. Expecting some errors :)

RV64Zca sample to get its Coverage

---

bin/covergroupgen.py

have added a condition for sltu instruction in covergroupgen.py.

Got 100% coverage of sltu RV64 instruction.

---

testplans/RV64F.csv

100% coverage RV64F 
- feq
- fle
- flt

100% coverage rv64 fle,flt,feq

---

Makefile
bin/testgen.py
templates/sample_RV32Zca.txt
templates/sample_RV32Zcb.txt
templates/sample_RV64Zca.txt
testplans/RV32Zcb.csv

Re-issued the PR # 180, also improved the Makefile after suggestion from Jordan. 
Tried to resolve the issue # 187 posted by Hamza Jamal.
Please let me know, if anything can be improved.

Related to solution of Issue # 187 

---

bin/testgen.py

* Wrote python function to load fp registers with different FLENs
* Maintains coverage for existing extensions
* More work needed to accommodate higher flen fp loads (e.g. fld)
* No new coverage, but a step towards getting all fp extensions simulating

updated testgen to make tests for different flen

---

bin/testgen.py

Due to some later PRs, coverage of catype was dropped down, I made some optimizations in code for catype to get it back to 100%.

optimized code for catype

---

bin/testgen.py
templates/cr_fs1_fs3_corners_frm.txt
templates/cr_fs1_fs3_corners_frm_D.txt
templates/cr_fs1_fs3_corners_frm_H.txt

@coreyqh some changes needed to be made to the RV32F and RV64F csvs to get to 100%, please propagate these to the other related csv's

100% coverage for FR4-type instructions

---

bin/covergroupgen.py
bin/testgen.py

finished coverage on fmv

---

bin/testgen.py

No issues with regression-wally --fcov

full coverage of fsqrt.s

---

bin/testgen.py

Almost 100% coverage. Sign injection at 100%, arithmetic at 92%+
To debug: none of the fflags seem to be hitting for half-precision instructions

added support for half precision frtype

---

bin/testgen.py

My bad, trying to resolve the merge conflict. And forgot to remove the third argument.

Resolve the issue that broke regression.

---

bin/testgen.py

* testgen no long makes hazard tests for unimplemented instructions
* Allows me to add extensions where certain instructions are causing issues (such as fround in ZfaF)
* No lost coverage

writeHazardVector refactor

---

bin/testgen.py

* New full coverage of 2 dozen or so instructions
* Improved coverage of nearly all others

Improved coverage across D, Zfh extensions

---

testplans/RV32Zicsr.csv
testplans/RV64Zicsr.csv

- included in testplans for RV32 and RV64

Zicsr.csv for RV32 and RV64

---

templates/cp_csr_fflags_v.txt

Propagated #308 into `cp_csr_fflags_v`

changed fflag nv test

---

templates/cp_fpr_hazard_r.txt
templates/cp_fpr_hazard_rw.txt
templates/cp_fpr_hazard_w.txt
templates/cp_gpr_hazard_r.txt
templates/cp_gpr_hazard_rw.txt
templates/cp_gpr_hazard_w.txt

These coverpoints are not in the testplans yet, so this should not affect current functionality. Testplans will need to be changed accordingly, which is still in progress.

added new coverpoints for float hazards

---

fcov/priv/ExceptionsM_coverage.svh
fcov/priv/ExceptionsU_coverage.svh
fcov/priv/ExceptionsU_coverage_init.svh

Almost identical to ExceptionsM with priv_mode_m changed for priv_mode_u, plus mstatus.sie added to cp_mstatus_ie

Created ExceptionsU covergroup

---

.gitmodules

Add riscvISACOV submodule

---

bin/testgen.py
templates/cp_imm5_corners.txt
testplans/RV32Zicsr.csv
testplans/RV64Zicsr.csv

- all Zicsr instructions at 92.50% 
- missing hazards, will talk to Hamza to fix 
- added coverpoint (cp_imm5_corners)

Improved Zicsr coverage

---

fcov/coverage/RISCV_instruction_base.svh

Updating signals to match the WallyTracer to match wally style

Updating signals to match wally Style

---

fcov/rv32_priv/RV_Assertions.sv

Template for RISC-V Assertions

Adding template for RV_Assertions

---

tests/lockstep/priv/EndianS.S

Completed and fully covered 1 of the 3 coverpoints for EndianS.

Coverpoint cp_sstatus_sbe_endianness_* fully covered

---

fcov/priv/ZicsrF_coverage.svh

Changed rs1_val to fs1_val for FPR coverpoints

---

bin/testgen.py
fcov/priv/ExceptionsS_coverage.svh

Test medeleg in ExceptionsS from machine mode

---

Makefile
fcov/rv32_priv/RV32VM_coverage.svh
fcov/rv64_priv/RV64VM_coverage.svh

This PR has all the changes that have been made to the SV32 and SV39 covergroups, with consultation between the team and @Huda-10xe.

Modification to VM Covergroups

---

fcov/coverage/RISCV_coverage_config.svh
fcov/priv/ExceptionsVM_coverage.svh
fcov/priv/ExceptionsVM_coverage_init.svh

Had to split some of the test plan coverpoints into fetch, load, and store variants.

ExceptionsVM covergroup

---

bin/testgen.py

fixed issues with raw hazards in flh and fsw

unpriv hazards at 100%

---

templates/coverage/cmp_rd_rs2_nx0.txt
templates/coverage/cp_rnum.txt
templates/coverage/cp_uimm.txt
templates/coverage/cp_uimm_n0.txt

Found this sitting around in one of my forks of the repo from a while ago.

Simplify a few coverpoints

---

fcov/coverage/RISCV_coverage_config.svh
fcov/priv/ExceptionsZicboS_coverage.svh
fcov/priv/ExceptionsZicboU_coverage.svh
tests/priv/ExceptionsZicboS.S
tests/priv/ExceptionsZicboU.S

Initial Draft for ZicboU/S test files.

ExceptionsZicboU/S Coverage

---

bin/testgen.py

worked on fixing the traps in the F and D extensions. Full coverage in rv32 and rv64

fixing trap for fsd, fsh

---

Makefile
bin/cvw-arch-verif.do
bin/sail-parse.py
bin/trace-coverreport.py

Adds scripts necessary to collect functional coverage from Sail
- Script to convert Sail log into trace for RVVI testbench
- Updates to cvw-arch-verif.do to work with RISCOF parameters
- Script to generate coverage from RISCOF based UCDBs

Functional coverage working with Sail

---

Makefile
bin/testgen.py
bin/vector-testgen.py

Separated vector and non-vector testgen into two files. Changed Makefile for this change too.

Separate vector and non-vector testgen

---

bin/vector-testgen.py

Deleted unnecessary arguments from several functions, added some comments, and renamed the instruction types according to testplan.

Cleaned up vector-testgen

---

fcov/priv/PMPF_coverage.svh

```
TYPE /RISCV_coverage_pkg/RISCV_coverage__1/PMPF_cg 
100.00%        100          -    Covered              
covered/total bins:                                    50         50          -                      
missing/total bins:                                     0         50          -                      
% Hit:                                            100.00%        100          -    
```

Aligned PMPF Coverpoints with the tests.
