Makefile
Ran into an error when running `make` and `make sim` where it would error out when the directories don't exist
=> updated makefile to create dirs if they don't exist

Makefile
Invoke with 
regression-wally --fcov
Look at reports in addins/cvw-arch-verif/work
=> Enabled coverage regression to test all RV32I instructions concurrently

bin/testgen.py
rs1 = rs2 = 31 case no longer produces invalid register 32
=> Fixed bug in fltype case in testgen.py

Makefile, bin/testgen.py
Modified **Makefile** to allow only Zc* extensions to get converted to 16-bit compressed instruction.
Found another bug which was preventing bins from being hit in cr_rs1_rs2_corners. Same register was used for both rs1 and rs2. For example:
`bin <min, max>`
rs1 is supposed to have minimum value (0x80000000) while rs2 maximum value (0x7fffffff). If rs1 and rs2 is the same register, it can't have both min and max simultaneously. 
Added few lines in testgen.py which prevents rs1 and rs2 being the same in cr_rs1_rs2_corners.
=> Achieved 100% coverage of RV32 add

bin/covergroupgen.py, bin/testgen.py
```
cp_asm_count : coverpoint ins.ins_str == "c.li"  iff (ins.trap == 0 )  {
option.comment = "Number of times instruction is executed";
bins count[]  = {1};
}
```
By changing "c.li" to "li", the bin was getting hit. But this modification was leading to errors because testgen.py uses this to recognize an instruction to generate its tests. This was fixed by 
```
cp_asm_count : coverpoint ins.ins_str == "li" || ins.ins_str == "c.li"  iff (ins.trap == 0 )  {
option.comment = "Number of times instruction is executed";
bins count[]  = {1};
}
```
This made the bin hit and testgen.py correctly recognized "c.li" as the instruction.
=> Fixed cp_asm_count for compressed instructions

bin/covergroupgen.py, bin/testgen.py
@davidharrishmc Thank you for pointing out that cp_asm_count for c.addi16sp and c.addi4spn are not being hit. 
I have added a dictionary in covergroupgen.py which handles all special cases like c.addi16sp, etc. We can add all special instructions in that dictionary and strip **'c.'** for other compressed instructions.
As for testgen.py, I have changed my approach to grab the compressed instruction's real name. 
```
option.comment = "c.addi4spn";
cp_asm_count : coverpoint ins.ins_str == "addi"  iff (ins.trap == 0 )  {
option.comment = "Number of times instruction is executed";
bins count[]  = {1};
}
```
**curinstr** was being fetched from the cp_asm_count line. I have adjusted the code such that if we are in a Zc* directory, we will fetch the instruction name from the previous line (from …
=> improved cp_asm_count for compressed instructions

templates/cp_csr_fflags_ndz_nuf.txt, testplans/RV32F.csv
Thought through this change and discussed with Prof. Harris, neither of these flags can be hit with `fadd` so  I created a new coverpoint with both of them excluded
=> removed dz and uf flags for fadd

bin/testgen.py, templates/cr_fs1_fs2_corners_frm.txt, testplans/RV32F.csv
Reverts openhwgroup/cvw-arch-verif#129
This PR set the rounding mode on all instructions.  Some instructions such as fmax don't use corners, so the assembly language doesn't compile.
=> Revert "100% coverage on fadd.s and fsub.s"

Makefile
covergroup files are now deleted by make clean
=> Updated make clean to clear covergroups in fcov/rv##/

bin/testgen.py
If fs3 is the same as either fs1 or fs2 during a corner case test, the value put into fs3 might override the corner value that actually needs to be tested. The same thing would happen if fs1=fs2 for an FR type instruction, but random chance might have saved us there. A change to randomize makes fs1, fs2, and fs3 all guaranteed to be different, so this overwriting can never happen.
=> bugfix for fr4 type corner coverpoints

templates/cp_fs1_corners.txt, templates/cp_fs2_corners.txt, templates/cp_fs3_corners.txt
This makes it possible to check that the proper value is held in the 64-bit floating-point registers in the rv64gc hardware configuration while maintaining the ability to use the same tests on a rv64f hardware configuration machine with 32-bit floating-point registers. 
This change gets 64-bit fsw to 100% and increases coverage for rv64f instructions with any of the cp_fs*_corners coverpoints. 
cp_fs*_corners_D coming soon for 64-bit floating-point register corner values.
=> Updated cp_fs*_corners to only check bottom 32 bits of floating-point register value

bin/testgen.py, templates/cp_fs1_corners_D.txt, templates/cp_fs2_corners_D.txt, templates/cp_fs3_corners_D.txt
Also made modifications to testgen.py to accommodate different flen when making tests to hit cp_fs*_corners. 
fcorners (implicitly single), fcornersD are defined with fcornersQ and fcornersH coming soon. 
make_fs*_corners takes a parameter for flen, which is default to "F"
In write_tests, when coverpoint == cp_fs*_corners_<precision>, make_fs*_corners is called with the flen parameter set to a string with the single letter precision (D, Q, H).
=> Created double precision fp corner values

Makefile, bin/testgen.py, templates/sample_RV32Zcb.txt, testplans/RV32Zcb.csv
Exclude checks from coverpoints like cp_rs1_corners, cp_rs1_toggle as rs1 is just a base address "scratch". Also exclude cp_fdp and cp_fs2p. Also made a change in makefile which is required. Please let me know, if anything can be improved.
=> c.sb & c.sh 100% Coverage

fcov/coverage/RISCV_instruction_base.svh, templates/sample_RV32Zca.txt, templates/sample_RV64Zca.txt
Some compressed instructions intended to be interpreted as swsp were instead being read as sw rs2 imm(x2), breaking regression. I made changes to RISCV_instruction_base.svh to properly interpret these instructions similar to the different versions of addi.
=> Compressed instruction bug fixes for sw/swsp

bin/testgen.py, testplans/RV32Zcb.csv
Excluded cp_rs1_toggle and cp_rs1_corners as rs1 is just a base address. And some templates like cp_rd_toggle_lbu & cp_rd_toggle_lhu were already there. So, I just used that.
=> c.lh, c.lhu & c.lbu 100% Coverage for RV32Zcb

bin/covergroupgen.py
Hitting 98.87% of bins. 
Only missing asm_count bin, which may not be possible to hit without an imperas fix.
This can be easily extended to other fmv* instructions should they also be aliased to depreciated names.
=> Near full coverage of fmv.x.w using alias fmv.x.s 

bin/testgen.py, templates/sample_RV64ZcbZba.txt, testplans/RV64ZcbZba.csv
While doing this, I faced a problem. **ZcbZba** is only for RV64, and testgen.py was trying to find RV32 coverage.svh file for it. As it couldn't find it, testgen.py was throwing an error and stopping execution. 
I made a modification in testgen.py, which we can use for extensions that are only made for RV64 or RV32.
=> RV64ZcbZba Done

bin/testgen.py
Rather than adding an additional loop in the make test functions, you can specify an rs1/rs2 in randomize, and also either force it to generate 3 unique registers or allow duplicates. No refactoring needed, but future code can be cleaner.
=> added ability to specify a (possibly unique) desired rs1/rs2 in randomize()

bin/testgen.py
Few changes to testgen to generate frm tests without having a cross product with the rounding mode (i.e. cp_frm_* without cr_fs*_fs*_frm*)
=> full coverage of fcvt*

bin/covergroupgen.py, fcov/coverage/RISCV_instruction_base.svh
sltiu with immediate value 1 was being replaced with seqz pseudo-instruction, which is resolved now. This improved coverage in both RV32I and RV64I sltiu.
=> Increased coverage for sltiu to 100%

Makefile
GCC 14 does not support Q and there are no Q tests currently. If we add Q later we can run the assembler directly.
=> Remove Q from march

bin/testgen.py
c.li, c.lwsp and c.ldsp were at 100%, but Hamza's latest PR #247 had a minor problem that dropped coverage of these instructions.  I found the problem and made changes appropriately. Now they're back at 100.
=> Fixed missing coverage of c.li,c.lwsp,c.ldsp 

bin/testgen.py, templates/sample_RV32ZcbM.txt, templates/sample_RV32ZcbZbb.txt, templates/sample_RV32Zcf.txt, templates/sample_RV64ZcbM.txt, templates/sample_RV64ZcbZba.txt, templates/sample_RV64ZcbZbb.txt
Some coverpoints that did not require specific test generation were not mentioned in testgen.py. It was causing warnings.
Also, sample templates for Zcb, ZcbZbb, ZcbZba & Zcf lacked proper spacing between **instruction name** and '**:**', due to which the instruction name was being misinterpreted as a coverpoint.
Added support for fdp, fs1p and fs2p.
About 30 warnings have been suppressed.
=> Fixed warnings for compressed instructions

bin/testgen.py
Fround instructions seem to cause mismatches depending on the pseudo random values they are given in source registers. Once this bug is fixed in Wally, these will be added back in.
=> Removes fround* to prevent regression failure

bin/testgen.py, templates/cp_fs1_fli.txt, templates/cp_rs1_fli.txt, testplans/RV32ZfaD.csv, testplans/RV32ZfaF.csv, testplans/RV32ZfaZfh.csv, testplans/RV64ZfaD.csv, testplans/RV64ZfaF.csv, testplans/RV64ZfaZfh.csv
* Created new coverpoint that checks the 5 bits of the rs1 field in the instruction binary, making sure each of the 32 values is exercised
* All FLI instructions are getting majority (87.5%) coverage, only missing hazard coverpoints
* FLI instructions should be fully covered once hazard refactoring is completed by the HMC team
=> FLI immediate coverpoint

bin/coverreport.py, fcov/rv32_priv/RV32VM_PMP_coverage.svh, fcov/rv32_priv/RV32VM_coverage.svh, fcov/rv64_priv/RV64CBO_PMP_coverage.svh, fcov/rv64_priv/RV64CBO_VM_coverage.svh, fcov/rv64_priv/RV64VM_PMP_coverage.svh, fcov/rv64_priv/RV64VM_coverage.svh, fcov/rv64_priv/RV64Zicbom_coverage.svh
Updating .svh coverage files for both 32 and 64 bits privilege coverage. Adding the trap condition on all page and access faults.
=> Adding trap condition for Page and Access Faults

bin/covergroupgen.py, fcov/priv/EndianM_coverage.svh, fcov/priv/EndianM_coverage_init.svh, fcov/priv/EndianS_coverage.svh, fcov/priv/EndianS_coverage_init.svh, fcov/priv/EndianU_coverage.svh, fcov/priv/EndianU_coverage_init.svh, fcov/priv/ZicsrM_coverage.svh, fcov/priv/ZicsrU_coverage.svh
* Moved existing endian coverpoints into their own designated covergroups
* Created new covergroup for supervisor mode endian coverpoints 
* Added several privilege extensions/features to covergroupgen.py
=> EndianS, EndianM, and EndianU Covergroups

Makefile
After compilation of SV32 tests, they are placed in a very odd arrangement. Within the vm_sv32/src folder there are separate folders for each test, each having two folders (dut & ref) within which elf files are placed. It becomes hectic to run the tests directly. Therefore, I added this code in makefile to make it easier. 
**make get_vm** looks within all the dut folders within vm_sv32/src and grabs **elf** files. They are then placed in a file **vm_tests.sh** in the form of 
```
wsim rv32gc /home/mzain/cvw/tests/riscof/work/riscv-arch-test/rv32i_m/vm_sv32/src/mstatus_tvm_test.S/dut/my.elf --fcov
wsim rv32gc /home/mzain/cvw/tests/riscof/work/riscv-arch-test/rv32i_m/vm_sv32/src/pmp_check_on_pa_S_mode.S/dut/my.elf --fcov
wsim rv32gc …
```
=> Modified Makefile to run SV32 tests

bin/combinetests.py, bin/covergroupgen.py, bin/coverreport.py, bin/csrtests.py, bin/illegalinstrtests.py, bin/testgen.py
Use paths relative to the location of the scripts in cvw-arch-verif where possible instead of depending on the `$WALLY` variable. This allows almost all of the scripts to be run without being a cvw addin. The only remaining references to `$WALLY` are in the Makefile for the temporary virtual memory tests and in the `coverreport.py` script because our ucdb files are generated in `cvw/sim`.
=> Use path based on arch-verif instead of $WALLY

tests/lockstep/priv/EndianM.S, tests/lockstep/priv/ExceptionsInstr.S, tests/lockstep/priv/ExceptionsInstrC.S, tests/lockstep/priv/ZicsrM.S
Realized that after the privileged tests were restructured, the path to `WALLY-init-lib` was broken. It'd be a good idea to come up with a way to parameterize this value, but in the meantime, this is a fix to allow the tests to run again
=> fixed init lib path

tests/lockstep/priv/EndianM.S
Changed register on line 137 to use s1 instead of s2, as the MBE bit has been stored in s1 at the top of the file
=> Fix typo in file EndianM.S

fcov/priv/EndianM_coverage.svh, fcov/priv/EndianS_coverage.svh, fcov/priv/EndianU_coverage.svh
Changed cp_{byte/half/word}offset to include valid offsets where imm[2:0] is not necessarily zero. I did this by checking the bottom 3 bits of the sum of imm and rs1_val and using wildcard ignore_bins to exclude auto-bins where bit 0 is 1 (for half word offset) and where either bit 0 or 1 is one (for word offset). This gives the following auto-bins in the report:
```
Coverpoint cp_byteoffset                          100.00%        100          -    Covered              
covered/total bins:                                 8          8          -                      
missing/total bins:                                 0          8          -                      
% Hit:                                        100.00%        100          -                      
bin auto[0] …
```
=> Improved byte, half, word offset coverpoints for Endian{M/S/U} covergroups

fcov/priv/ExceptionsM_coverage.svh, fcov/priv/ExceptionsU_coverage.svh
* The original auto bins conflicted the test plan and were impossible to hit if C is not supported
resolves #445
=> Removed potentially impossible PC bins

fcov/coverage/RISCV_coverage_config.svh
If a coverage file requires multiple extensions it will be automatically selected if all of those extensions are enabled instead of needing to be manually enabled.
=> Simplify coverage extension selection

fcov/priv/ZicntrM_coverage.svh, fcov/priv/ZicntrM_coverage_init.svh, fcov/priv/ZicntrS_coverage.svh, fcov/priv/ZicntrS_coverage_init.svh, fcov/priv/ZicntrU_coverage.svh, fcov/priv/ZicntrU_coverage_init.svh
Renamed counter covergroups to be consistent with other covergroups by prepending the test plan name.
=> Renamed covergroups

fcov/priv/ZicsrS_coverage.svh
The mode bits of satp can be written in s mode, so attempts to write them in S mode tests cause things to go haywire. One cross product used `csr_no_satp`, already, which is now used for both cross products that attempt writes to all csr addresses.
=> Removed satp from 4096 csr arguments

fcov/priv/ExceptionsM_coverage.svh, fcov/priv/ExceptionsS_coverage.svh, fcov/priv/ExceptionsU_coverage.svh
Bit swizzled bins for taken and not taken branches are never hit. @C0d3ing fixed this in one of the three exceptions files by concatenating the values into a single 6 bit binary literal. This applies those changes throughout.
=> Fixed bit swizzled bins

fcov/coverage/RISCV_coverage_standard_coverpoints.svh, fcov/priv/EndianM_coverage.svh, fcov/priv/EndianS_coverage.svh, fcov/priv/EndianU_coverage.svh, fcov/priv/ExceptionsM_coverage.svh, fcov/priv/ExceptionsS_coverage.svh, fcov/priv/ExceptionsU_coverage.svh, fcov/priv/ExceptionsZicboS_coverage.svh, fcov/priv/ExceptionsZicboU_coverage.svh, fcov/priv/InterruptsM_coverage.svh, fcov/priv/InterruptsS_coverage.svh, fcov/priv/InterruptsSstc_coverage.svh, fcov/priv/InterruptsU_coverage.svh, fcov/priv/ZicntrM_coverage.svh, fcov/priv/ZicntrS_coverage.svh, fcov/priv/ZicntrU_coverage.svh, fcov/priv/ZicsrM_coverage.svh, fcov/priv/ZicsrS_coverage.svh, fcov/priv/ZicsrU_coverage.svh, fcov/rv32_priv/RV32CBO_VM_coverage.svh, fcov/rv32_priv/RV32VM_coverage.svh, fcov/rv64_priv/RV64CBO_VM_coverage.svh, fcov/rv64_priv/RV64VM_coverage.svh
Adds a new standard coverpoint file that can be included in other coverpoints to reduce duplication of basic coverpoints. As a proof of concept this is used for priv_mode coverpoints.
All priv mode coverpoints are also switched to use prev to get the privilege mode at the end of the previous instruction.
=> Add standard coverpoint file and update priv mode to use prev

fcov/coverage/RISCV_coverage_csr.svh
Added the vector CSRs that were missing from the CSR list in fcov/coverage/RISCV_coverage_csr.svh, namely vcsr, vl, vlenb, vstart, and vxsat.
Modified/added the VS field in CSR mstatus and vsstatus. Note that mstatus had a different VS field specification, and the new number is based on the new RISC-V spec.
=> Added all vector CSRs in the CSR list

fcov/rv32_priv/RV32VM_coverage.svh, fcov/rv64_priv/RV64VM_coverage.svh
I have added the required coverpoints for DAU faults.
Misaligned coverpoints were not properly written, which have been fixed by using a function to check appropriate bits. Also its bins were being hit irrespective of the type of page (misaligned mega page was hitting bins for both mega and giga).
Some corrections are also made to the canonical coverpoints.
=> Incorporated DAU coverpoints to VM

fcov/rv32_priv/RV32VM_coverage.svh
When trying to run make sim there were coverpoint issues in rv32_priv/RV32VM_coverage.svh
Please advise if these fixes are correct since I am unfamiliar with page types.
After my changes `make sim` executes correctly.
Changes:
created bins giga under coverpoint PageType_i and PageType_d
Renamed cover points to have unique bin names from lines 707 to 729 in the change log
=> RV32VM_coverage Coverpoints

tests/WALLY-init-lib.h
Ensure that mscratch has a value for the trap handler to work with before doing anything that may trap (like accessing CSRs that may or may not exist). Fixes #531
=> Setup mscratch before accessing CSRs that may not exist without certain extensions

fcov/priv/ExceptionsVM_coverage.svh
Was breaking regression because I switched the physical address bit widths between rv32 and rv64
=> Fixed phys addr bit width bug

fcov/priv/ExceptionsVM_coverage.svh
Minor typo in the coverage file for the ExceptionsVM covergroup
=> ExceptionsVM CoverGroup Typo Fix

Makefile
With the vectors files having SEW in their file names, e.g. Vx32/Vx64, the current MABI and BITWIDTH logic causes confusion and failing makefile. Changed makefile so that the two are searching for "rv32" and "rv64" instead of simply "32" and "64."
=> modified makefile logic for MABI and BITWIDTH

fcov/priv/InterruptsS_coverage.svh
Had to change a bunch of coverpoints to make them consistent with the idea of "you can't get interrupts in S-mode if mideleg is 0 for that interrupt." Recommended changes to the test plan are in the Interrupts google sheet.
=> InterruptsS tests at 80% coverage

templates/coverage/sample_VVVX.txt
Template for vector instruction type VVVX did not exist, added a sample template for it.
Example VVVX instruction:
vmv1r.v  vd, vs2
=> Added sample template of vector instruction type VVVX

bin/covergroupgen.py
covergroupgen.py generated Vx on top of Vx8, Vx16, Vx32, Vx64. Updated so that Vx is no longer generated and prevents confusion.
=> update on covergroupgen to not generate Vx

bin/testgen.py
spike had an error of "Currently the 'V' implementation requires the 'M' extension." Changed ISA string for the vector .S file to address this.
Vector tests have a data sections which stores a number of words and making the file really big. Reduced the number of words to reduce the size of the file. Still thinking of the most logical way to address the number of random vector which testgen generates.
=> Reducing vector .S file size and supporting M for V

templates/coverage/cp_vd_widen.txt, templates/coverage/cp_vs2_widen.txt
Added templates for cp_vd_widen and cp_vs2_widen to account that widened registers should exclude v31 as they are included in v30.
=> Widening coverpoint templates for vd and vs2

bin/testgen.py, templates/coverage/cmp_vd_vs2_widen.txt, templates/coverage/cp_vs2_widen.txt
Modified testgen and a few coverpoint templates to address widening vector instructions. Few notes from the spec regarding the changes:
- When LMUL=2, the vector register group contains vector register v n and vector register v n+1, providing twice the vector length in bits. Instructions specifying an LMUL=2 vector register group with an odd-numbered vector register are reserved.
- A vector register cannot be used to provide source operands with more than one EEW for a single instruction.
=> testgen modification for vector widening instructions

fcov/rv64_priv/RV64VM_coverage.svh
Enabled coverage for sv48, which included sv48 in crosses. Most of the changes are just ignoring tera page for sv39.
=> Made changes to SV48 coverpoints

bin/vector-testgen.py
Modified vector-testgen for slide/gather/compress and mask logical instructions. Basic coverpoints and tests for all vector instructions (other than load/store and vset) should work and collect coverage now.
=> Vector testgen modify for slide/gather and mask logical instructions

bin/sail-parse.py, fcov/testbench.sv
In testbench.sv, all regVal was assigned to be XLEN long, which cuts the values held by double FP and vector registers, and causing issues with coverage.
sail parsing errors are also included in this PR.
=> Fixed critical error on testbench having XLEN for all types of registers

fcov/coverage/RISCV_coverage_standard_coverpoints_vector.svh, fcov/coverage/RISCV_coverage_vector.svh, fcov/priv/ZicsrV_coverage.svh
Changed naming of get_vlmax to get_vtype_vlmax to make clear that the vlmax is being calculated from the current CSR values.
The function used to terminate vsim if vill bit is set, which is causing an issue in priv tests. Changed vlmax to return -1 if vill bit is set.
=> Fixed vlmax function naming and changed vill consequence

Makefile, bin/sail-parse.py, bin/vector-testgen-unpriv.py, pyproject.toml
- Migrate `.ruff.toml` to `pyproject.toml` so a single file can be used for all python related configuration going forward.
- Add `make lint` and `make lint-fix` targets to make it easy to manually run lint.
=> Migrate ruff config and add Make targets

fcov/priv/PMPS_coverage.svh, fcov/priv/PMPU_coverage.svh
```
TYPE /RISCV_coverage_pkg/RISCV_coverage__1/PMPU_cg 
100.00%        100          -    Covered              
covered/total bins:                                   579        579          -                      
missing/total bins:                                     0        579          -                      
% Hit:                                            100.00%        100          -             
```
```
TYPE /RISCV_coverage_pkg/RISCV_coverage__1/PMPS_cg 
100.00%        100          -    Covered              
covered/total bins:                                   579        579          -                      
missing/total bins:                                     0        579          -                      
% Hit:                                            100.00%        100 …
```
=> Modified the PMPS and PMPU Coverpoints.

fcov/priv/PMPM_coverage.svh
Changed the names of coverpoint for tor all. Prevously they were cp_cfg_A_tor_all, but they actually should have been addr_for_tor_all because configuration check is being performed in RWXL_i001_pmp1cfg coverpoints.
Updated the definition of cover point pmpcfg_tor_bot_L0 and pmpcfg_tor_bot_L1 to correctly check the value for pmpcfg0[15:0] bit field.
Added a single coverpoint for straddling address start and end instead of having 3 seperate coverpoints with same bin definition.
Updated the coverpoint first_four_pmp_entries on request of @sudo-apt-abdullah .
=> adjusted PMPM coverpoints according to tests written

fcov/priv/PMPM_coverage.svh
For coverpoint cp_cfg_A_tor_nonoverlap we have 3 test cases each time with a different pmpaddr0 value. Since the region is locked, so I have created 3 seperate test files to implement 3 test cases. The coverpoint definition is updated for each of those test cases named as 1, 2 and 3.
=> adjusted coverpoints for tor non overlap in PMPM

fcov/rv64_priv/RV64CBO_VM_coverage.svh
I have added new coverpoints for cbo.zero to VM_CBO. We have a coverpoint for Zicbom where R=1 and W=0 and it's not supposed to fault. As discussed in our previous meeting, I have added a new coverpoint where R=0, W=0 & X=1 which is supposed to fault.
I have updated the names of coverpoints. They had write in them, which I think should be changed because write might confuse someone in thinking that it's either the permission of PTE or we're using some store instruction. I have updated it to cbo, zicbom & zicboz respectively (where cbo represents both zicbom & zicboz). 
Some coverpoints for Zicboz are different from Zicboz such as
* D bit unset is supposed to fault for Zicboz while not for Zicbom
* Zicbom instructions will fault when (R=0 & W=0) and not when (R=1 & W=0).
* While zicboz …
=> Added Zicboz coverpoints to VM_CBO
